### ISSUE TITLE
Exception upon loading in after Nexus transfer

### ISSUE THREAD

**Issue by jrloken** [Allen-Wrench/CreativeWorldSave#1]
I've been getting this exception after transferring servers via the Nexus client since I installed CreativeWorldSave today:
```
2023-04-28 23:09:44.244 - Thread:   1 ->  Exception occurred: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sandbox.Game.GameSystems.Chat.MyChatCommandSystem.ScanAssemblyForCommands(Assembly assembly)
   at CreativeWorldSave.Plugin.AddCommand()
   at System.Action.Invoke()
   at System.DelegateExtensions.InvokeIfNotNull(Action handler)
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   ```

Let me know if more info is needed, happy to help troubleshoot

**Comment by Allen-Wrench** [comment]
oh, interesting... Ill check it out right now. and thank you, the information provided is perfect :)

**Comment by Allen-Wrench** [comment]
it appears that the chat command system does not do any checks when its adding commands, so it got angry when the plugin tried to add the same command again. apparently the command system sticks around longer than i expected, because seamless is doing seamless things, so i just had to stop an event from triggering after it runs the first time. the plugin should update once its approved for the plugin loader.
